name: DynamicTextures
author: TfT_02
main: com.me.tft_02.dynamictextures.DynamicTextures
description: Multiple texturepacks for one server!
dev-url: http://dev.bukkit.org/server-mods/worldtextures/
version: 1.2.3
softdepend: [WorldGuard]
commands:
   dynamictextures:
      description: Get information about the plugin.
      permission-message: You don't have <permission>
permissions:
    dynamictextures.change_texturepack:
        description: Change texturepack for this player.
        default: true