name: DynamicTextures
version: 1.3.0
description: >
  Multiple ResourcePacks for one server! With DynamicTextures you can set
  a ResourcePack for each world, or even WorldGuard region.

author: TfT_02
website: http://dev.bukkit.org/server-mods/worldtextures/

main: com.me.tft_02.dynamictextures.DynamicTextures
softdepend: [Multiverse-Core, WorldGuard]
load: POSTWORLD

commands:
   dynamictextures:
      description: Get information about the plugin.
      permission-message: You don't have <permission>

permissions:
    dynamictextures.commands.reload:
        description: Allow use of the /dynamictextures reload command
        default: OP
    dynamictextures.commands.refreshall:
        description: Allow use of the /dynamictextures refreshall command
        default: OP
    dynamictextures.resourcepack:
        description: Change ResourcePacks for this player.
        default: true
